/**
 * Gpio_Private.h
 *
 *  Created on: Sat Apr 19 2024
 *  Author    : Omar Abd El-nasser
 */

#ifndef GPIO_PRIVATE_H
#define GPIO_PRIVATE_H

#define GPIOX_BASE_ADDRESS 0x40000000

/* GPIO portA Registers addresses*/
#define GPIOA_BASE_ADDR (GPIOX_BASE_ADDRESS + 0x00020000)
#define GPIOA_MODER 	REG32(GPIOA_BASE_ADDR, 0x00)
#define GPIOA_OTYPER 	REG32(GPIOA_BASE_ADDR, 0x04)
#define GPIOA_OSPEEDR 	REG32(GPIOA_BASE_ADDR, 0x08)
#define GPIOA_PUPDR 	REG32(GPIOA_BASE_ADDR, 0x0C)
#define GPIOA_IDR 		REG32(GPIOA_BASE_ADDR, 0x10)
#define GPIOA_ODR 		REG32(GPIOA_BASE_ADDR, 0x14)
#define GPIOA_BSRR 		REG32(GPIOA_BASE_ADDR, 0x18)
#define GPIOA_LCKR 		REG32(GPIOA_BASE_ADDR, 0x1C)
#define GPIOA_AFRL 		REG32(GPIOA_BASE_ADDR, 0x20)
#define GPIOA_AFRH 		REG32(GPIOA_BASE_ADDR, 0x24)
#define GPIOA_PUPDR_RESET_VALUE 0x64000000UL


/* GPIO portB Registers addresses*/
#define GPIOB_BASE_ADDR (GPIOX_BASE_ADDRESS + 0x00020400)
#define GPIOB_MODER 	REG32(GPIOB_BASE_ADDR, 0x00)
#define GPIOB_OTYPER 	REG32(GPIOB_BASE_ADDR, 0x04)
#define GPIOB_OSPEEDR 	REG32(GPIOB_BASE_ADDR, 0x08)
#define GPIOB_PUPDR 	REG32(GPIOB_BASE_ADDR, 0x0C)
#define GPIOB_IDR 		REG32(GPIOB_BASE_ADDR, 0x10)
#define GPIOB_ODR 		REG32(GPIOB_BASE_ADDR, 0x14)
#define GPIOB_BSRR 		REG32(GPIOB_BASE_ADDR, 0x18)
#define GPIOB_LCKR 		REG32(GPIOB_BASE_ADDR, 0x1C)
#define GPIOB_AFRL 		REG32(GPIOB_BASE_ADDR, 0x20)
#define GPIOB_AFRH 		REG32(GPIOB_BASE_ADDR, 0x24)
#define GPIOB_PUPDR_RESET_VALUE 0x00000100UL
#define PULL_UP_PORTB           0x00000100UL
#define PULL_DOWN_PORTB         0x00001000UL


/* GPIO portC Registers addresses*/
#define GPIOC_BASE_ADDR (GPIOX_BASE_ADDRESS + 0x00020800)
#define GPIOC_MODER 	REG32(GPIOC_BASE_ADDR, 0x00)
#define GPIOC_OTYPER 	REG32(GPIOC_BASE_ADDR, 0x04)
#define GPIOC_OSPEEDR 	REG32(GPIOC_BASE_ADDR, 0x08)
#define GPIOC_PUPDR 	REG32(GPIOC_BASE_ADDR, 0x0C)
#define GPIOC_IDR 		REG32(GPIOC_BASE_ADDR, 0x10)
#define GPIOC_ODR 		REG32(GPIOC_BASE_ADDR, 0x14)
#define GPIOC_BSRR 		REG32(GPIOC_BASE_ADDR, 0x18)
#define GPIOC_LCKR 		REG32(GPIOC_BASE_ADDR, 0x1C)
#define GPIOC_AFRL 		REG32(GPIOC_BASE_ADDR, 0x20)
#define GPIOC_AFRH 		REG32(GPIOC_BASE_ADDR, 0x24)

/* GPIO portD Registers addresses*/
#define GPIOD_BASE_ADDR (GPIOX_BASE_ADDRESS + 0x00020C00)
#define GPIOD_MODER 	REG32(GPIOD_BASE_ADDR, 0x00)
#define GPIOD_OTYPER 	REG32(GPIOD_BASE_ADDR, 0x04)
#define GPIOD_OSPEEDR 	REG32(GPIOD_BASE_ADDR, 0x08)
#define GPIOD_PUPDR 	REG32(GPIOD_BASE_ADDR, 0x0C)
#define GPIOD_IDR 		REG32(GPIOD_BASE_ADDR, 0x10)
#define GPIOD_ODR 		REG32(GPIOD_BASE_ADDR, 0x14)
#define GPIOD_BSRR 		REG32(GPIOD_BASE_ADDR, 0x18)
#define GPIOD_LCKR 		REG32(GPIOD_BASE_ADDR, 0x1C)
#define GPIOD_AFRL 		REG32(GPIOD_BASE_ADDR, 0x20)
#define GPIOD_AFRH 		REG32(GPIOD_BASE_ADDR, 0x24)


/* GPIO portE Registers addresses*/
#define GPIOE_BASE_ADDR (GPIOX_BASE_ADDRESS + 0x00021000)
#define GPIOE_MODER 	REG32(GPIOD_BASE_ADDR, 0x00)
#define GPIOE_OTYPER 	REG32(GPIOD_BASE_ADDR, 0x04)
#define GPIOE_OSPEEDR 	REG32(GPIOD_BASE_ADDR, 0x08)
#define GPIOE_PUPDR 	REG32(GPIOD_BASE_ADDR, 0x0C)
#define GPIOE_IDR 		REG32(GPIOD_BASE_ADDR, 0x10)
#define GPIOE_ODR 		REG32(GPIOD_BASE_ADDR, 0x14)
#define GPIOE_BSRR 		REG32(GPIOD_BASE_ADDR, 0x18)
#define GPIOE_LCKR 		REG32(GPIOD_BASE_ADDR, 0x1C)
#define GPIOE_AFRL 		REG32(GPIOD_BASE_ADDR, 0x20)
#define GPIOE_AFRH 		REG32(GPIOD_BASE_ADDR, 0x24)


/* GPIO portH Registers addresses*/
#define GPIOH_BASE_ADDR (GPIOX_BASE_ADDRESS + 0x00021C00)
#define GPIOH_MODER 	REG32(GPIOD_BASE_ADDR, 0x00)
#define GPIOH_OTYPER 	REG32(GPIOD_BASE_ADDR, 0x04)
#define GPIOH_OSPEEDR 	REG32(GPIOD_BASE_ADDR, 0x08)
#define GPIOH_PUPDR 	REG32(GPIOD_BASE_ADDR, 0x0C)
#define GPIOH_IDR 		REG32(GPIOD_BASE_ADDR, 0x10)
#define GPIOH_ODR 		REG32(GPIOD_BASE_ADDR, 0x14)
#define GPIOH_BSRR 		REG32(GPIOD_BASE_ADDR, 0x18)
#define GPIOH_LCKR 		REG32(GPIOD_BASE_ADDR, 0x1C)
#define GPIOH_AFRL 		REG32(GPIOD_BASE_ADDR, 0x20)
#define GPIOH_AFRH 		REG32(GPIOD_BASE_ADDR, 0x24)


#endif /* GPIO_PRIVATE_H */
